### ISSUE TITLE
How to start?

### ISSUE THREAD

**Issue by nishuo1999** [19801201/SpinalHDL_CNN_Accelerator#2]
我已经安装了能够运行spinalHDL官方模板的环境，在Intellij上运行，但是我如何运行该加速器？在命令行中使用sbt run 导入依赖库会卡在这一步
[info] set current project to spinal_yolo_dev (in build file:/D:/project/spianl/spianl_CNN_nishuo/SpinalHDL_CNN_Accelerator/)
  | => spinalhdl_cnn_accelerator / update 102s

**Comment by liuwei9** [comment]
把整个代码下载下来放到相应目录就可以了
